apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-fakeshop
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      annotations: #annotations são pares chave-valor que podem armazenar dados adicionais ao objeto 
        prometheus.io/scrape: 'true'   #permite o prometheus coletar dados da aplicação
        prometheus.io/port: '5000'     #qual porta ele vai coletar os dados
        prometheus.io/path: '/metrics' #qual endpoint ele vai coletar os dados
      labels:
        app: fakeshop
    spec:
      containers:
      - name: fakeshop-app
        image: caiovrodrigues/fake-shop
        env:
        - name: DB_HOST
          value: service-db
        - name: DB_USER
          value: caiovrodrigues
        - name: DB_PASSWORD
          value: ${{secrets.DB_PASSWORD}}
        - name: DB_NAME
          value: ${{secrets.DB_NAME}}
        - name: FLASK_APP
          value: index.py
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service-fakeshop
spec:
  selector:
    app: fakeshop
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
