apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-fakeshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      labels:
        app: fakeshop
    spec:
      containers:
      - name: fakeshop-app
        image: caiovrodrigues/fake-shop:latest
        env:
        - name: DB_HOST
          value: service-db
        - name: DB_USER
          value: caiovrodrigues
        - name: DB_PASSWORD
          value: ${{secrets.DB_PASSWORD}}
        - name: DB_NAME
          value: ${{secrets.DB_NAME}}
        - name: FLASK_APP
          value: index.py
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service-fakeshop
spec:
  selector:
    app: fakeshop
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
