apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-fakeshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      labels:
        app: fakeshop
    containers:
    - name: fakeshop-app
      image: caiovrodrigues/fake-shop:latest
      ports:
      - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service-fakeshop
spec:
  selector:
    app: fakeshop
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
